name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install tmux
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux
        tmux -V
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: NODE_ENV=test npm test
    
    - name: Start tmux session for testing
      run: |
        # Start a detached tmux session for testing
        tmux new-session -d -s test-session
        # List sessions to verify
        tmux ls
    
    - name: Run integration tests
      run: |
        echo "Running integration tests..."
        # Set environment to use tmux backend for tests
        npm run test:integration
      continue-on-error: false

    